# Generated by Django 5.2.15 on 2026-06-05 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='reports/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('bureau', models.CharField(choices=[('equifax', 'Equifax'), ('experian', 'Experian'), ('transunion', 'TransUnion'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('match_confidence', models.CharField(blank=True, choices=[('ssn', 'SSN Match'), ('ssn_last4_name', 'SSN Last-4 + Name'), ('name_dob', 'Name + DOB'), ('manual', 'Manual'), ('', 'Unmatched')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_text', models.TextField(blank=True)),
                ('page_count', models.IntegerField(default=0)),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='identities.identity')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
