# Generated by Django 5.2.15 on 2026-06-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('archived', 'Archived')], default='pending', max_length=20),
        ),
    ]
