# Generated by Django 5.2.15 on 2026-06-05 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identities', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonresult',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='reports.creditreport'),
        ),
        migrations.AddField(
            model_name='identity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='identities.identity'),
        ),
        migrations.AlterUniqueTogether(
            name='comparisonresult',
            unique_together={('identity', 'report', 'field_name')},
        ),
    ]
