# Generated by Django 5.2.15 on 2026-06-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='identity',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='identity',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='identity',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
