# Generated by Django 5.2.15 on 2026-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='expected_fico_range',
            field=models.CharField(blank=True, choices=[('800-850', '800-850 (Exceptional)'), ('740-799', '740-799 (Very Good)'), ('670-739', '670-739 (Good)'), ('580-669', '580-669 (Fair)'), ('300-579', '300-579 (Poor)')], max_length=10),
        ),
    ]
