# Generated by Django 5.2.15 on 2026-06-05 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0003_identity_city_identity_state_identity_street_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='city',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='state',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='street',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='zip_code',
        ),
        migrations.CreateModel(
            name='IdentityAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('address_type', models.CharField(choices=[('current', 'Current'), ('previous', 'Previous'), ('other', 'Other')], default='current', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='identities.identity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
