# Generated by Django 5.2.15 on 2026-06-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0003_identity_expected_fico_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityaccount',
            name='account_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='identityaccount',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='identityaccount',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='identityaccount',
            name='date_opened',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identityaccount',
            name='highest_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='identityaccount',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
