# Generated by Django 5.2.15 on 2026-06-09 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0004_identityaccount_account_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdentityEmail',
        ),
    ]
