# Generated by Django 5.2.15 on 2026-06-05 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0004_remove_identity_city_remove_identity_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], max_length=1),
        ),
        migrations.CreateModel(
            name='IdentityEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=254)),
                ('email_type', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('other', 'Other')], default='personal', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='identities.identity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IdentityNameVariation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_variations', to='identities.identity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IdentityPhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('phone_type', models.CharField(choices=[('mobile', 'Mobile'), ('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='mobile', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='identities.identity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
