# Generated by Django 5.2.15 on 2026-06-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0005_add_gender_name_variations_phones_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10),
        ),
    ]
