# Generated by Django 5.2.15 on 2026-06-05 15:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('address_type', models.CharField(choices=[('current', 'Current'), ('previous', 'Previous'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('reported_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='AlternateName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('account_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('auto_loan', 'Auto Loan'), ('mortgage', 'Mortgage'), ('student_loan', 'Student Loan'), ('personal_loan', 'Personal Loan'), ('collection', 'Collection'), ('medical', 'Medical'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('derogatory', 'Derogatory'), ('collection', 'In Collections'), ('charged_off', 'Charged Off'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_opened', models.DateField(blank=True, null=True)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('ssn', models.CharField(blank=True, max_length=15)),
                ('ssn_last_four', models.CharField(blank=True, max_length=4)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
