# Generated by Django 5.2.15 on 2026-06-05 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='reports.creditreport'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to='entities.subject'),
        ),
        migrations.AddField(
            model_name='alternatename',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_names', to='entities.subject'),
        ),
        migrations.AddField(
            model_name='address',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='entities.subject'),
        ),
    ]
