# Generated by Django 5.2.15 on 2026-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='account_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='highest_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='credit_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='in_file_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='score_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
