# Generated by Django 5.2.15 on 2026-06-05 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonresult',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='reports.creditreport'),
        ),
        migrations.AddField(
            model_name='referencedata',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_data', to='cases.case'),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='cases.referencedata'),
        ),
    ]
