# Generated by Django 5.2.15 on 2026-06-08 19:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('sample_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(choices=[('full_name', 'Full Name'), ('ssn', 'SSN / Tax ID'), ('date_of_birth', 'Date of Birth'), ('address', 'Address'), ('phone', 'Phone'), ('email', 'Email'), ('employer', 'Employer'), ('account_number', 'Account Number'), ('custom', 'Custom Field')], max_length=50)),
                ('custom_label', models.CharField(blank=True, max_length=50)),
                ('regex_pattern', models.TextField()),
                ('capture_group', models.PositiveSmallIntegerField(default=1)),
                ('case_insensitive', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='doctemplates.documenttemplate')),
            ],
            options={
                'ordering': ['order', 'field_name'],
            },
        ),
    ]
